### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by yzn-h** [khonsulabs/kludgine#55]
![image](https://user-images.githubusercontent.com/63852512/166626253-4a69217f-89dd-4a47-95ab-096ae1001328.png)
the Arabic text is reversed and not joint correctly

**Comment by yzn-h** [comment]
there is a way around it using [arabic_reshaper](https://crates.io/crates/arabic_reshaper) and [unicode_reverse](https://crates.io/crates/unicode-reverse) it works

**Comment by ecton** [comment]
I haven't been maintaining this library recently (I've been focusing on [BonsaiDb](https://github.com/khonsulabs/bonsaidb), and the font rendering is quite outdated -- it's been on my list to update to a maintained crate. I would love to see this in Kludgine eventually, but if this is important for you in the near term, it might be better to consider other libraries.

Thank you for checking this project out and providing the feedback!

**Comment by yzn-h** [comment]
If you can recommend me a rendering library that RTL support I will really appreciate it

**Comment by yzn-h** [comment]
https://github.com/RazrFalcon/rustybuzz
support RTL

**Comment by ecton** [comment]
I spent some time looking at the current state of things, and the library I'm most interested in is [fontdue](https://github.com/mooman219/fontdue). Right now, however, it does not support shaping, but I can't find a rasterization library that supports shaping. Their readme states that it's a future goal, however.

Right now Kludgine uses `rusttype`, which a high-level API that allows you to ask it to rasterize glyphs, and it provides the actual pixel data. Rustybuzz provides all the shape information, but adopting it would require implementing font rasterization and texture atlasing manually.

Given the limited time I'm putting into this library at this time, this isn't something that I could whip up quickly. I'm hoping that libraries such as `fontdue` reach their goals, so that I can reuse the efforts from such a library.

If there is a library that provides shaping and rasterization and doesn't have tricky build dependencies, I would try to get it incorporated -- but I'm not sure such a thing exists yet.

**Comment by yzn-h** [comment]
can this be used? https://github.com/grovesNL/glyphon it is build with cosmic-text for wgpu

**Comment by ecton** [comment]
Even if it can't, I could adopt `cosmic-text` with `etagere` like `glyphon` is doing. Thank you for pointing this out!

I'm not sure how quickly I'll be getting around to this, however. While I do keep releasing updates, it's mostly because I don't want this library to get outdated as wgpu continues to evolve. I am not currently actively using it, although I keep thinking I might again soon.

**Comment by ecton** [comment]
This has been implemented and tested in the rewrite occurring in #60.

![rtl](https://github.com/khonsulabs/kludgine/assets/50053/fe0f2f59-f7d6-417b-9210-0cf2675d5315)

I will close this once the version with RTL support has been published to crates.io.

**Comment by ecton** [comment]
[v0.6.0](https://github.com/khonsulabs/kludgine/releases/tag/v0.6.0) which utilizes cosmic_text has been released!
